name: Buf

on:
  pull_request:
    types: [ opened, synchronize, reopened, labeled, unlabeled ]
    paths:
      - "**/*.proto"
      - .github/workflows/buf.yml
      - buf.yaml
      - README.md
  push:
    paths:
      - "**/*.proto"
      - .github/workflows/buf.yml
      - buf.yaml
      - README.md
  delete:
    paths:
      - "**/*.proto"
      - .github/workflows/buf.yml
      - buf.yaml
      - README.md

permissions:
  contents: read
  pull-requests: write

jobs:
  buf:
    name: Buf Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
          github_token: ${{ github.token }}
