name: Buf

on:
  pull_request:
    paths:
      - "**/*.proto"
      - .github/workflows/buf.yml
      - buf.yaml
  push:
    paths:
      - "**/*.proto"
      - .github/workflows/buf.yml
      - buf.yaml

jobs:
  buf:
    name: Buf Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bufbuild/buf-action@v1
        with:
          token: ${{ secrets.BUF_TOKEN }}
