name: Docker

on:
  pull_request:
    paths:
      - .github/workflows/docker.yml
      - Dockerfile
      - CMakeLists.txt
      - libmediocre/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/docker.yml
      - Dockerfile
      - CMakeLists.txt
      - libmediocre/**
  release:
    types:
      - "published"

jobs:

  build_test_push:
    name: Build, test and push image
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            obroomhall/mediocre
          sep-tags: ",\n"
          tags: |
            type=sha
            type=sha,suffix=-cache
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=ref,event=branch,suffix=-cache
            type=ref,event=tag,suffix=-cache
            type=ref,event=pr,suffix=-cache
      -
        name: Docker background pull
        env:
          to_pull: ${{ format('{0}{1}{2}', '[', steps.meta.outputs.tags, ']') }}
        run: |
          docker pull $to_pull
      -
        name: Check out the repo
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Log in to Docker Hub
        uses: docker/login-action@v2
        env:
          DOCKER_USERNAME: obroomhall
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      -
        name: Build and push sha image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: ${{ steps.meta-sha.outputs.tags }}
          labels: ${{ steps.meta-sha.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      -
        # This is genuinely faster than load:true on previous step
        # I know, I can barely believe it either
        name: Pull sha image
        run: |
          docker pull ${{ steps.meta-sha.outputs.tags }} # should only be one tag
      -
        name: Install testing tools
        env:
          GRPC_CLIENT_CLI_VERSION: 1.18.0
        run: curl -L -s https://github.com/vadimi/grpc-client-cli/releases/download/v${{ env.GRPC_CLIENT_CLI_VERSION }}/grpc-client-cli_linux_x86_64.tar.gz | tar -C /usr/local/bin -xz
      -
        name: Start container
        run: |
          docker run -d --rm --name mediocre -p 127.0.0.1:80:50051/tcp ${{ steps.meta-sha.outputs.tags }}
          export max_retries=20
          export cur_retries=0
          until [[ $(grpc-client-cli health 127.0.0.1:80 | jq -r '.status') == 'SERVING' ]]; do
            if (( $cur_retries >= $max_retries )); then exit 1; fi
            echo "Waiting for a healthy container...($cur_retries/$max_retries)"
            sleep 0.05
            export cur_retries=$((cur_retries+1))
          done
          echo "Container is healthy!"
      -
        name: Check OpenCV
        run: |
          check_opencv=$(echo '{}' | grpc-client-cli -service Dependency -method CheckOpenCV 127.0.0.1:80)
          echo $check_opencv && [[ $(echo $check_opencv | jq '.healthy') == 'true' ]]
      -
        name: Check Tesseract
        run: |
          check_tesseract=$(echo '{}' | grpc-client-cli -service Dependency -method CheckTesseract localhost:80)
          echo $check_tesseract && [[ $(echo $check_tesseract | jq '.healthy') == 'true' ]]
      -
        name: Stop container
        run: docker stop mediocre
      -
        # This doesn't actually build, since the cache was exported in the other docker/build-push-action step
        name: Re-tag and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
