name: Docker

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
  release:
    types:
      - "published"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG_PREFIX: ${{ github.event_name == 'release' && '' || 'dev-' }}
      DOCKER_TAG_SUFFIX: ${{ github.head_ref || github.ref_name }}
      DOCKER_REPOSITORY: obroomhall/mediocre
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Check if base dockerfile has changed
        id: base-dockerfile-changed
        uses: tj-actions/changed-files@v36
        with:
          files: "Base.Dockerfile"
          since_last_remote_commit: true
          
      - name: Get tag names
        id: get-tags
        run: |
          echo "docker-base-tag=${{ format('{0}:base-{1}{2}', env.DOCKER_REPOSITORY, env.DOCKER_TAG_PREFIX, env.DOCKER_TAG_SUFFIX) }}" >> $GITHUB_OUTPUT
          echo "docker-base-fallback-tag=${{ format('{0}:base-{1}master', env.DOCKER_REPOSITORY, env.DOCKER_TAG_PREFIX) }}" >> $GITHUB_OUTPUT
          echo "docker-main-tag=${{ format('{0}:{1}{2}', env.DOCKER_REPOSITORY, env.DOCKER_TAG_PREFIX, env.DOCKER_TAG_SUFFIX) }}" >> $GITHUB_OUTPUT
          
      - name: Print tag names
        id: print-tags
        run: |
          echo "docker-base-tag=${{ steps.get-tags.outputs.docker-base-tag }}"
          echo "docker-base-fallback-tag=${{ steps.get-tags.outputs.docker-base-fallback-tag }}"
          echo "docker-main-tag=${{ steps.get-tags.outputs.docker-main-tag }}"

      - name: Build and push base Docker image
        if: steps.base-dockerfile-changed.outputs.any_changed == 'true'
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: Base.Dockerfile
          push: true
          tags: ${{ steps.get-tags.outputs.docker-base-tag }}

      - name: Check base image exists, otherwise use fallback
        id: find-base-image
        run: |
          echo "Looking for base image ${{ steps.get-tags.outputs.docker-base-tag }}"
          export base_image_exists=$(docker manifest inspect ${{ steps.get-tags.outputs.docker-base-tag }} >/dev/null 2>&1)
          echo "Base image $([[ $base_image_exists -eq 0 ]] && echo "does not exist" || echo "exists")"
          echo "base-image-exists=$base_image_exists" >> $GITHUB_OUTPUT

      - name: Build and push main Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: BASE_TAG=${{ steps.find-base-image.outputs.base-image-exists && steps.get-tags.outputs.docker-base-tag || steps.get-tags.outputs.docker-base-fallback-tag }}
          tags: ${{ steps.get-tags.outputs.docker-main-tag }}
