name: Docker

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"
  release:
    types:
      - "published"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG_PREFIX: ${{ github.event_name == 'release' && '' || 'dev-' }}
      DOCKER_TAG_SUFFIX: ${{ github.head_ref || github.ref_name }}
      DOCKER_REPOSITORY: obroomhall/mediocre
      DOCKER_BASE_TAG: ${{ env.DOCKER_REPOSITORY ':base-' env.DOCKER_TAG_PREFIX env.DOCKER_TAG_SUFFIX }}
      DOCKER_BASE_FALLBACK_TAG: ${{ env.DOCKER_REPOSITORY ':base-' env.DOCKER_TAG_PREFIX 'master' }}
      DOCKER_TAG: ${{ env.DOCKER_REPOSITORY ':' env.DOCKER_TAG_PREFIX env.DOCKER_TAG_SUFFIX }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Check if base dockerfile has changed
        id: base-dockerfile-changed
        uses: tj-actions/changed-files@v36
        with:
          files: "Base.Dockerfile"
          since_last_remote_commit: true

      - name: Build and push base Docker image
        if: steps.base-dockerfile-changed.outputs.any_changed == 'true'
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: Base.Dockerfile
          push: true
          tags: ${{ env.DOCKER_BASE_TAG }}

      - name: Check base image exists, otherwise use fallback
        id: find-base-image
        run: |
          echo "Looking for base image ${{ env.DOCKER_BASE_TAG }}"
          docker manifest inspect ${{ env.DOCKER_BASE_TAG }} > /dev/null
          export base_image_exists=$?
          echo "Base image $([[ $base_image_exists -eq 0 ]] && echo "does not exist" || echo "exists")"
          echo "base-image-exists=$base_image_exists" >> $GITHUB_OUTPUT

      - name: Build and push main Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: Dockerfile
          push: true
          build-args: BASE_TAG=${{ steps.find-base-image.outputs.base-image-exists && env.DOCKER_BASE_TAG || env.DOCKER_BASE_FALLBACK_TAG }}
          tags: obroomhall/mediocre:${{ env.DOCKER_TAG }}
