name: Preview Destroy

on:
  pull_request:
    types: [ closed ]

jobs:

  destroy:
    name: Destroy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: scripts/deploy
          sparse-checkout-cone-mode: false
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.STAGING_SSH_KEY }}
      - name: Setup known hosts
        run: ssh-keyscan -H ${{ secrets.STAGING_IP }} >> ~/.ssh/known_hosts
      - name: Destroy Preview
        working-directory: scripts/deploy
        run: |
          ssh ${{ secrets.STAGING_USER }}@${{ secrets.STAGING_IP }} \
            "bash -s ${{ github.event.number }}" \
            < destroy-preview.sh
