name: VCPKG

on:
  push:
    paths:
      - .github/workflows/vcpkg.yml
      - CMakeLists.txt
      - grpc/**
      - mediocre/**
      - scripts/**

permissions:
  contents: write

env:
  VCPKG_FEATURE_FLAGS: dependencygraph
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Install vcpkg
        run: |
          sudo apt install curl zip unzip tar
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg && ./bootstrap-vcpkg.sh && cd ..
      - name: Run vcpkg
        run: ${{ github.workspace }}/vcpkg/vcpkg install