name: VCPKG

on:
  push:
    paths:
      - .github/workflows/vcpkg.yml
      - CMakeLists.txt
      - grpc/**
      - mediocre/**
      - scripts/**

permissions:
  contents: write

env:
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install vcpkg
        run: |
          sudo apt install curl zip unzip tar
          git clone https://github.com/microsoft/vcpkg.git
          cd vcpkg && ./bootstrap-vcpkg.sh && cd ..
      - name: Run vcpkg
        run: ${{ github.workspace }}/vcpkg/vcpkg install --dry-run